### ISSUE TITLE
Static analysis by @phpstan

### ISSUE THREAD

**Issue by szepeviktor** [BinaryMoon/wp-toolbelt#21]
Are you interested in the tool?

```
 ------ --------------------------------------
  Line   admin/index.php
 ------ --------------------------------------
  239    Variable $to might not be defined.
  240    Variable $from might not be defined.
  249    Variable $to might not be defined.
  250    Variable $from might not be defined.
  259    Variable $to might not be defined.
  260    Variable $from might not be defined.
 ------ --------------------------------------

 ------ --------------------------------------------------------------------------------------------------------
  Line   modules/breadcrumbs/index.php
 ------ --------------------------------------------------------------------------------------------------------
  52     Variable $breadcrumb might not be defined.
  110    Function toolbelt_breadcrumb_tax_hierarchical() should return string but empty return statement found.
  176    Function toolbelt_get_term_parents() should return string but returns WP_Error.
  183    Function jetpack_get_term_parents not found.
 ------ --------------------------------------------------------------------------------------------------------

 ------ -----------------------------------------------------------------
  Line   modules/cleanup/index.php
 ------ -----------------------------------------------------------------
  27     Function remove_action invoked with 4 parameters, 2-3 required.
  28     Function remove_action invoked with 4 parameters, 2-3 required.
  31     Function remove_action invoked with 4 parameters, 2-3 required.
  32     Function remove_action invoked with 4 parameters, 2-3 required.
 ------ -----------------------------------------------------------------

 ------ ------------------------------------------------------------------------------------------------------------
  Line   modules/disable-comment-urls/index.php
 ------ ------------------------------------------------------------------------------------------------------------
  17     Parameter $author_link of function toolbelt_disable_comment_author_links() has invalid typehint type type.
  35     Function toolbelt_comment_form_fields() should return string but returns array.
 ------ ------------------------------------------------------------------------------------------------------------

 ------ -------------------------------------------------------------------------------------------------------
  Line   modules/social-menu/index.php
 ------ -------------------------------------------------------------------------------------------------------
  62     Function toolbelt_social_menu_svg() never returns null so it can be removed from the return typehint.
  130    Cannot access property $theme_location on array.
  140    Cannot access property $link_after on array.
 ------ -------------------------------------------------------------------------------------------------------

 ------ -----------------------------------------------------------------
  Line   modules/social-sharing/index.php
 ------ -----------------------------------------------------------------
  60     Variable $_SERVER in isset() always exists and is not nullable.
 ------ -----------------------------------------------------------------
```

**Comment by BinaryMoon** [comment]
I haven't seen this before but it's a nice report. Thanks :)

**Comment by szepeviktor** [comment]
`phpstan.neon.dist`

```yaml
#$ composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress
#$ vendor/bin/phpstan analyze -l 4
includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/modules/
        - %currentWorkingDirectory%/admin/
    autoload_files:
        - %currentWorkingDirectory%/index.php
        - %currentWorkingDirectory%/admin/index.php
        # Modules
        - %currentWorkingDirectory%/modules/breadcrumbs/index.php
        - %currentWorkingDirectory%/modules/cleanup/index.php
        - %currentWorkingDirectory%/modules/cookie-banner/index.php
        - %currentWorkingDirectory%/modules/disable-comment-urls/index.php
        - %currentWorkingDirectory%/modules/fast-404/index.php
        - %currentWorkingDirectory%/modules/featured-attachment/index.php
        - %currentWorkingDirectory%/modules/heading-anchors/index.php
        - %currentWorkingDirectory%/modules/lazy-load/index.php
        - %currentWorkingDirectory%/modules/projects/index.php
        - %currentWorkingDirectory%/modules/random-redirect/index.php
        - %currentWorkingDirectory%/modules/related-posts/index.php
        - %currentWorkingDirectory%/modules/responsive-videos/index.php
        - %currentWorkingDirectory%/modules/social-menu/index.php
        - %currentWorkingDirectory%/modules/social-sharing/index.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function add_query_arg invoked with [123] parameters?, 0 required\.$#'
```
